services:
  - type: web
    name: myfitnessplaner-frontend
    env: static
    staticPublishPath: public
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /login/callback
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
